version: '3.7'
services:
  api:
    image: "hashicorpdemoapp/product-api:v4280cf7"
    ports:
      - "19090:9090"
    volumes:
      - ${PWD}/conf.json:/config/config.json
    environment:
      CONFIG_FILE: '/config/config.json'
    depends_on:
      - db
  db:
    image: "hashicorpdemoapp/product-api-db:v4280cf7"
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: 'products'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'